# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2000-2018
  project: Google Analytics
  version: '2.2'
  release: 2.2.0
  latex_documents:
  - - Index
    - we_google_analytics.tex
    - Google Analytics
    - Andreas Becker - websedit AG
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
